"""
Underchex - A hexagonal chess variant game engine

Python implementation matching the TypeScript reference.

Signed-by: agent #17 claude-sonnet-4 via opencode 20260122T05:47:09
"""

from .types import (
    HexCoord,
    Direction,
    DIRECTIONS,
    ALL_DIRECTIONS,
    DIAGONAL_DIRECTIONS,
    LANCE_A_DIRECTIONS,
    LANCE_B_DIRECTIONS,
    PieceType,
    Color,
    LanceVariant,
    Piece,
    Move,
    GameStatus,
    GameState,
    BOARD_RADIUS,
    PROMOTION_TARGETS,
    coord_to_string,
    string_to_coord,
    coords_equal,
    opposite_color,
    is_promotion_zone,
)

from .board import (
    is_valid_cell,
    get_all_cells,
    add_direction,
    get_neighbor,
    get_neighbors,
    hex_distance,
    get_direction,
    get_ray,
    get_cells_between,
    KNIGHT_OFFSETS,
    get_knight_targets,
)

from .moves import (
    get_forward_direction,
    get_pawn_capture_directions,
    get_piece_directions,
    is_slider,
    get_piece_at,
    is_occupied,
    has_enemy,
    has_friendly,
    generate_pseudo_legal_moves,
    find_king,
    is_attacked,
    is_in_check,
    apply_move,
    generate_legal_moves,
    generate_all_legal_moves,
    validate_move,
)

from .game import (
    get_starting_position,
    create_board_from_placements,
    create_new_game,
    make_move,
    resign,
    is_player_turn,
    get_legal_moves,
    is_current_player_in_check,
)

from .openingbook import (
    BookMoveStats,
    BookEntry,
    BookMetadata,
    OpeningBook,
    BookLookupOptions,
    BookLookupResult,
    GameForBook,
    BookGenerationOptions,
    BookStatistics,
    get_opening_book,
    set_opening_book,
    clear_opening_book,
    get_book_entry,
    is_in_book,
    get_book_size,
    calculate_win_rate,
    lookup_book_move,
    add_game_to_book,
    generate_opening_book,
    prune_book,
    serialize_book,
    deserialize_book,
    export_book_to_json,
    import_book_from_json,
    load_book_from_json,
    save_book_to_file,
    load_book_from_file,
    get_book_statistics,
    format_book_entry,
)

__version__ = "0.1.0"
__all__ = [
    # Types
    "HexCoord",
    "Direction",
    "DIRECTIONS",
    "ALL_DIRECTIONS",
    "DIAGONAL_DIRECTIONS",
    "LANCE_A_DIRECTIONS",
    "LANCE_B_DIRECTIONS",
    "PieceType",
    "Color",
    "LanceVariant",
    "Piece",
    "Move",
    "GameStatus",
    "GameState",
    "BOARD_RADIUS",
    "PROMOTION_TARGETS",
    "coord_to_string",
    "string_to_coord",
    "coords_equal",
    "opposite_color",
    "is_promotion_zone",
    # Board
    "is_valid_cell",
    "get_all_cells",
    "add_direction",
    "get_neighbor",
    "get_neighbors",
    "hex_distance",
    "get_direction",
    "get_ray",
    "get_cells_between",
    "KNIGHT_OFFSETS",
    "get_knight_targets",
    # Moves
    "get_forward_direction",
    "get_pawn_capture_directions",
    "get_piece_directions",
    "is_slider",
    "get_piece_at",
    "is_occupied",
    "has_enemy",
    "has_friendly",
    "generate_pseudo_legal_moves",
    "find_king",
    "is_attacked",
    "is_in_check",
    "apply_move",
    "generate_legal_moves",
    "generate_all_legal_moves",
    "validate_move",
    # Game
    "get_starting_position",
    "create_board_from_placements",
    "create_new_game",
    "make_move",
    "resign",
    "is_player_turn",
    "get_legal_moves",
    "is_current_player_in_check",
    # Opening Book
    "BookMoveStats",
    "BookEntry",
    "BookMetadata",
    "OpeningBook",
    "BookLookupOptions",
    "BookLookupResult",
    "GameForBook",
    "BookGenerationOptions",
    "BookStatistics",
    "get_opening_book",
    "set_opening_book",
    "clear_opening_book",
    "get_book_entry",
    "is_in_book",
    "get_book_size",
    "calculate_win_rate",
    "lookup_book_move",
    "add_game_to_book",
    "generate_opening_book",
    "prune_book",
    "serialize_book",
    "deserialize_book",
    "export_book_to_json",
    "import_book_from_json",
    "load_book_from_json",
    "save_book_to_file",
    "load_book_from_file",
    "get_book_statistics",
    "format_book_entry",
]
